
[env]
TERM = "xterm-256color"

[font]
size = 14
# normal = {family = "Iosevka NerdFont"}
normal = {family = "Fira Code"}

[font.offset]
x = 0
y = 0

[general]
import = ["/home/dmitri/.config/alacritty/gruvbox_dark.toml"]
